# MongoDB remains unchanged
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Flask-Mongodb-Test-Project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Flask-Mongodb-Test-Project
  template:
    metadata:
      labels:
        app: Flask-Mongodb-Test-Project
    spec:
      containers:
        - name: Flask-Mongodb-Test-Project
          image: iyedhosni20/Flask-Mongodb-Test-Project:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: Flask-Mongodb-Test-Project-service
spec:
  selector:
    app: Flask-Mongodb-Test-Project
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31701
  type: NodePort
